insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('1','5','Bien')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('2','1','Deficiente')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('3','4','Casi bien')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('4','5','Bien')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('5','5','Bien')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('6','1','Deficiente')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('7','3','Regular')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('8','3','Regular')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('9','5','Bien')
insert into calificacionEntity(ID, NUMEROEST, DESCRIPCION) values ('10','5','Bien')
